### ISSUE TITLE
Syntax definition

### ISSUE THREAD

**Issue by laughedelic** [idris-hackers/atom-language-idris#1]
As you have this point in the TODO list:
> Improve the syntax-highlighting (the current is base on the Sublime plugin)

I suggest to collaborate on it. I've made some progress [here](https://github.com/laughedelic/sublime-idris) (see yaml file), but I'm not very good in defining textmate scopes and there are some not defined things yet (see TODO comment at the bottom). So if you are interested, take it to your atom plugin and welcome to suggest improvements.

**Comment by archaeron** [comment]
@laughedelic I'm extracting some of your highlighting rules from here: https://github.com/laughedelic/sublime-idris/blob/master/Idris.YAML-tmLanguage

I know this is late. But are you still interested in cooperation?

**Comment by laughedelic** [comment]
Sure! I'm glad that it appeared to be useful somewhere else. Actually I'm using Atom now, so I'm interested in helping with the plugin.

**Comment by archaeron** [comment]
please, you are very welcome to :) there are tickets for the issues I know of. maybe tell me what you'd like to work on, so that we're not doing duplicate work

**Comment by archaeron** [comment]
I'm closing this issue in favour of concrete examples. I'm happy to fix something if I know what.
