### ISSUE TITLE
Can't restart the compiler when it was stopped

### ISSUE THREAD

**Issue by justjoheinz** [idris-hackers/atom-language-idris#106]
When I edit an idris file and typecheck it a couple of time and issue the command `Idris: stop compiler` there does not seem to be a way to restart it again. Subsequent typechecking fails with an exception: `Uncaught TypeError: Cannot read property 'length' of undefined`.

**Comment by bobgus** [comment]
When I do Packages->Typecheck an idris file in Atom, I get two red panels to the right - which disappear too quickly. If I repeat the command, nothing happens.

Quit Atom, then repeat 'idris ops.idr' in a terminal, then do ':e' to open Atom, then do Packages->Typecheck, and quickly look at the red panels - it is saying in one that it cannot find idris - but path it reports there is correct. The other red panel reports that idris has crashed, probably error -2. When I look in another terminal string 'ps ax | grep idris', it shows idris as still there.

Bobs-Air:src bobgus$ ps ax | grep idris
  863 s002  S+     0:04.88 idris ops.idr
  932 s003  S+     0:00.00 grep idris

I am running OS X El Capitan on a Mac air. I am very new to both Atom and Idris (too new perhaps..) I can get idris to perform in a terminal, but Atom is another beast.

**Comment by justjoheinz** [comment]
This issue is fixed
