### ISSUE TITLE
Add a REPL

### ISSUE THREAD

**Issue by archaeron** [idris-hackers/atom-language-idris#11]
ide-mode should make this easy.
http://docs.idris-lang.org/en/latest/reference/ide-protocol.html#protocol-overview `(:interpret STRING)`

the only thing we have to think about is how to display the repl

Ideas:
TextEditorView with mini: true gives an input
https://www.npmjs.com/package/atom-space-pen-views#constructor-params

**Comment by archaeron** [comment]
Repl progress:
![repl2](https://cloud.githubusercontent.com/assets/471043/7803341/43e0351a-034d-11e5-9903-b4f0e779f727.PNG)

**Comment by Heather** [comment]
:+1:

**Comment by archaeron** [comment]
added in v0.4.0 (#80)
