### ISSUE TITLE
Enhance looking for compiler options in pkgs option of ipkg files

### ISSUE THREAD

**Issue by justjoheinz** [idris-hackers/atom-language-idris#110]
It is nice that compiler options are read from the ipkg file, e.g. 
```
opts = "-p effects -p lightyear -p contrib --warnpartial"
```

This is however not the same as 
```
opts = "--warnpartial"

pkgs = effects, lightyear, contrib
```
where the packages to include are not recognized by Atom, thus code does not typecheck in the later style.

**Comment by archaeron** [comment]
this:

```
package test

modules = Test
main = Test

opts = "--warnpartial"

pkgs = effects, lightyear, contrib
```
generates these compiler options:
```
"{"options":"--warnpartial","pkgs":["effects","lightyear","contrib"]}"
```

which are passed like this to the compiler:
`-p effects lightyear contrib --warnpartial`

this on the other hand:
```
package test

modules = Test
main = Test

opts = "-p effects -p lightyear -p contrib --warnpartial"
```

is made into:
```
"{"options":"-p effects -p lightyear -p contrib --warnpartial","pkgs":[]}"
```
which is turned into:
`-p effects -p lightyear -p contrib --warnpartial`

So my guess if it's not working is that id needs the `-p` in front of every package
