### ISSUE TITLE
Nested with blocks

### ISSUE THREAD

**Issue by edwinb** [idris-hackers/atom-language-idris#112]
If I have the following code:

```
data SnocList : List a -> Type where
     Empty : SnocList []
     Snoc : {xs : List a} -> {x : a} -> SnocList (xs ++ [x])

snocList : (xs : List a) -> SnocList xs
snocList [] = Empty
snocList (x :: xs) with (snocList xs)
  snocList (x :: []) | Empty = Snoc {xs = []} {x = x}
  snocList (x :: (ys ++ [y])) | Snoc = Snoc {xs = x :: ys} {x = y}

palindrome : DecEq a => List a -> Bool
palindrome [] = True
palindrome (x :: xs) with (snocList xs)
  palindrome (x :: []) | Empty = True
  palindrome (x :: (ys ++ [y])) | Snoc = ?palindrome_rhs_2
```

Then I press Ctrl-Alt-W on the last line, to get a new with block, I get:

```
palindrome : DecEq a => List a -> Bool
palindrome [] = True
palindrome (x :: xs) with (snocList xs)
  palindrome (x :: []) | Empty = True
  palindrome (x :: (ys ++ [y])) | Snoc with (_)
    palindrome (x :: (ys ++ [y])) | Snoc | with_pat = ?_rhs
```

That is, I get a name `_rhs` rather than what I'd expect which is `?palindrome_rhs`

I believe the problem is just that the cursor is moving to the beginning of the line to pick up the name rather than the first non-whitespace character in the line.

(This is probably easy to fix, and most likely my fault in the first place, so apologies for not just doing it myself... I'm frantically hacking on Chapter 10 of the TypeDD book, which uses this exact example, so don't want to be diverted too much just now! I'll come back to this if someone else doesn't get there first)

(EDIT: Removed spaces at the start of code snippet)

**Comment by archaeron** [comment]
Hello

the example I have here: https://github.com/archaeron/atom-language-idris-tests/commit/37e5a9f9881bc2ed713ef21556a055a1332b874e doesn't compile and I'm not capable of fixing it at the moment.

This means I can't even test this out :) sorry

**Comment by edwinb** [comment]
Curious - what error message are you getting? I don't think this requires any recent fixes but I could be wrong...

**Comment by archaeron** [comment]
interesting. I tried this today again and it's working.
I updated yesterday to 0.10.3. is it possible that this didn't compile with 0.10.0?

**Comment by edwinb** [comment]
I suppose it is possible. I did fix a couple of silly errors recently.... thanks for the quick fix anyway!

**Comment by archaeron** [comment]
let's hope it was that :D
And you're welcome.
