### ISSUE TITLE
Consider using `cmd` instead of `alt` for OS X keybindings

### ISSUE THREAD

**Issue by karljs** [idris-hackers/atom-language-idris#116]
I have been trying Atom over Emacs for Idris on my OS X laptop and find using the `alt` or `option` key in addition to `ctrl` to be really uncomfortable.  I would strongly suggest considering using `cmd` and `ctrl` together instead on OSX .

If it comes down to "PRs welcome" I'd be happy to oblige.  I think it should be basically a simple copy paste with minor edits.

**Comment by archaeron** [comment]
I'm hoping to have more time in a few weeks, until then "PRs welcome" :)

**Comment by karljs** [comment]
I took a swing at it.  As mentioned in the PR, I really haven't had the time to figure out Atom package development so I just did my best based on some Google searches.  Please let me know if there is a better approach.

**Comment by dwijnand** [comment]
Fixes as of #117.
