### ISSUE TITLE
Go to declaration

### ISSUE THREAD

**Issue by pocorall** [idris-hackers/atom-language-idris#119]
Right click on any function in source code, select "Go to Declaration" does nothing.

Is there any other way to do this? IMO, it is very important for new language learners to easily navigate standard library.

**Comment by archaeron** [comment]
hello

sorry for the delay. I didn't know Atom now has "Go to definition" built in.

There is an alternative way of achieving something similar. Have you tried opening the command palette (CTRL+SHIFT+P on windows) when you have some code highlighted and typed "Print Definition"?

This should show you the definition and is hopefully similar to what you want.

**Comment by pocorall** [comment]
Thanks! "Print definition" feature is super cool. I added a keyboard shortcut for this function in my keymap file.

**Comment by archaeron** [comment]
I'm very glad the feature is helping you :)
