### ISSUE TITLE
Helping with package maintenance

### ISSUE THREAD

**Issue by jonboiser** [idris-hackers/atom-language-idris#122]
I saw your tweet earlier today and wanted to offer my help. I'm just learning Idris myself, but have decent experience with Atom development. 

I personally think having this available for Atom is important for Idris adoption and making it accessible, so I'd be happy to contribute this way.

**Comment by archaeron** [comment]
Hey
this is great news!
There is someone else who has interest in this, but the more people put a bit of work into this the better :)

Maybe you could post here as well:
https://groups.google.com/forum/#!topic/idris-lang/Kn4m5b_HnIg

**Comment by melted** [comment]
@jonboiser You're welcome to help!

**Comment by justjoheinz** [comment]
Really everyone should help, nevertheless I close the issue :-)
