### ISSUE TITLE
The ide-mode closes when the idris code contains an error

### ISSUE THREAD

**Issue by archaeron** [idris-hackers/atom-language-idris#13]
the ide-mode closes when the idris code contains an error

Minimal example:
```idris
module Test

a
```

**Comment by Heather** [comment]
@archaeron or if .ibc is created with another idris version

**Comment by archaeron** [comment]
@Heather cool, thanks. I haven't had that bug :)

**Comment by archaeron** [comment]
@david-christiansen could you take a look at this?

setup:

file test.idr
```idris
module Test

a
```

start idris in ide mode:

```sh
..\idris-win64-0.9.18\idris.exe --ide-mode
```

load the file:

```
000018(:protocol-version 1 0)
00004f((:load-file "C:\Users\UserName\Documents\Programming\Idris\Start\test.idr") 1)
000111(:output (:ok (:highlight-source ((((:filename "C:\\Users\\UserName\\Documents\\Programming\\Idris\\Start\\test.idr") (:start 1 8) (:end 1 12)) ((:namespace "Test") (:decor :module) (:source-file "C:\\Users\\UserName\\Documents\\Programming\\Idris\\Start\\test.idr")))))) 1)
000111(:output (:ok (:highlight-source ((((:filename "C:\\Users\\UserName\\Documents\\Programming\\Idris\\Start\\test.idr") (:start 1 8) (:end 1 12)) ((:namespace "Test") (:decor :module) (:source-file "C:\\Users\\UserName\\Documents\\Programming\\Idris\\Start\\test.idr")))))) 1)
idris.exe: src\Idris\Parser.hs:(1276,40)-(1279,67): Non-exhaustive patterns in case
```

and then the compiler closes

**Comment by david-christiansen** [comment]
Would you please paste the contents of your code?

**Comment by archaeron** [comment]
https://gist.github.com/archaeron/46ff50b5ecf5ef53d4e0

this is all I need to crash the ide-mode :)

**Comment by archaeron** [comment]
@david-christiansen would you lke me to open an issue on idris-dev with a step by step guide on how to reproduce the error and what I expected to happen?

**Comment by david-christiansen** [comment]
Please!

**Comment by archaeron** [comment]
done: https://github.com/idris-lang/Idris-dev/issues/2317

**Comment by david-christiansen** [comment]
The underlying Idris issue should be fixed in `master`. Would you please confirm that it's now fixed?

**Comment by archaeron** [comment]
I can confirm that it's working with a freshly built idris from `master`.

thanks, this helps a lot!
