### ISSUE TITLE
Add autocompletion

### ISSUE THREAD

**Issue by archaeron** [idris-hackers/atom-language-idris#14]
the ide-mode can provide completion. Use it together with http://blog.atom.io/2015/05/15/new-autocomplete.html.

First experimentations here: https://github.com/idris-hackers/atom-language-idris/tree/autocomplete-tests

**Comment by justjoheinz** [comment]
I will close this. It works, though everything is displayed as "function". Unfortunately the idris reponse `(:return (:ok (("liftA" "liftA2" "liftA3" "liftPrimIO" "liftPrimIO") "")) 1)` does not contain more information.

**Comment by david-christiansen** [comment]
We could pretty easily update the Idris response to contain more information than it does (perhaps the info given by `:apropos`, which is type signature and the overview from the docs?). That's totally doable, and I can point you at the spot in the code where it would need doing if you'd like.
