### ISSUE TITLE
Make a 0.4.6 release

### ISSUE THREAD

**Issue by melted** [idris-hackers/atom-language-idris#140]
There has been quite a few commits since the last release.

**Comment by melted** [comment]
I'm pretty sure I can put this together in the next few days.

**Comment by melted** [comment]
Wrote some release notes for 0.4.5 so it doesn't look so tiny on the release page :-)

**Comment by justjoheinz** [comment]
@melted It would be lovely if you could look and improve https://github.com/idris-hackers/atom-language-idris/pull/141 before we make a release.

**Comment by melted** [comment]
Done!
