### ISSUE TITLE
Idris version 0.4.6

### ISSUE THREAD

**Issue by justjoheinz** [idris-hackers/atom-language-idris#148]
@melted I had thought that version 0.4.6 has already been released, but https://atom.io/packages/language-idris still show 0.4.5 as the recent version. Did the release fail or was it indeed not yet released?

**Comment by melted** [comment]
Yeah, I ran into authentication trouble. Apparently it wasn't enough to have write access to the repo. So if @archaeron could allow https://atom.io/users/melted to update the package it would be nice.

**Comment by archaeron** [comment]
@melted I don't think I have any settings. And you have already published 0.4.5

**Comment by archaeron** [comment]
@melted apm tries to push via git. Maybe it doesn't pick up your credentials

**Comment by melted** [comment]
Hmmm, I think it worked now.

**Comment by archaeron** [comment]
awesome! :)
