### ISSUE TITLE
Deprecated selector in `language-idris/styles/highlight.atom-text-editor.less`

### ISSUE THREAD

**Issue by juliendhouti** [idris-hackers/atom-language-idris#153]
In `language-idris/styles/highlight.atom-text-editor.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .gutter .line-number.highlight-idris-error` => `atom-text-editor.editor .gutter .line-number.highlight-idris-error`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by justjoheinz** [comment]
Me thinks this has been fixed with commit  86e9adbd6608da28bd20519d874a724fcfd003d8

**Comment by melted** [comment]
So it was!
