### ISSUE TITLE
Ubuntu Keybinding for ctrl-alt-t is low-level open terminal

### ISSUE THREAD

**Issue by pjgoodall** [idris-hackers/atom-language-idris#159]
Keybinding ctrl-alt-t opens a system terminal window on Ubuntu when used within language-idris editor in Atom. This keybinding seems to be very low-level within ubuntu, and none of the tools with atom such as ctrl-. work on it.

The display of keybindings within the language-idris plugin does not let me change a single key-binding, but discards all. I don't want to be an Atom or Ubuntu system expert right now - I have enough to learn.

Ubuntu 16.04 LTS is pretty mainstream, can we put an easy to manage keybinding onto that platform please.

**Comment by justjoheinz** [comment]
For the time being you can invoke the command "Application: Open your keymap" and insert

```
'atom-text-editor[data-grammar~="idris"]':
  'ctrl-alt-t': 'language-idris:type-of'
```

and replace `ctrl-alt-t` with a keybinding of your preference.
Other keybindings can be found by going into the Idris settings and click on the left symbol to copy the according command into your clipboard.

In case you found a working set of keybindings, we can see if they can be included into the package or find another solution.

**Comment by pjgoodall** [comment]
Thank-you Markus,

Much-appreciated. I am using 'ctrl-alt-y'  successfully for the moment - as
in tYpe.

Cheers...

**Comment by pjgoodall** [comment]
Hi all,

‘ctrl-alt-i’ collides with ‘System Lock Screen’ in Ubuntu 16.04, and
probably other Ubuntii

I replaced with:

'atom-text-editor[data-grammar~="idris"]':
  'ctrl-alt-e': 'language-idris:make-lemma'

for *lEmma*

Cheers,
—Peter G
​

**Comment by melted** [comment]
Should we try to use other modifiers than ctrl-alt on linux?

> 12 apr. 2017 kl. 08:29 skrev pjgoodall <notifications@github.com>:
> 
> Hi all,
> 
> ‘ctrl-alt-i’ collides with ‘System Lock Screen’ in Ubuntu 16.04, and
> probably other Ubuntii
> 
> I replaced with:
> 
> 'atom-text-editor[data-grammar~="idris"]':
> 'ctrl-alt-e': 'language-idris:make-lemma'
> 
> for *lEmma*
> 
> Cheers,
> —Peter G
> ​
>

**Comment by justjoheinz** [comment]
Is this really related to ubuntu, or rather the specific window manager and/or window manager plugins?
As a first step we should amend the README to explain how to customize keyboard bindings for language-atom. I will do that over the easter holidays. I am a bit reluctant to change the modifiers, because they are probably all over the TDD book now.

**Comment by corazza** [comment]
I think Ctrl+Alt+T is a GNOME+Debian legacy, or even purely Ubuntu, but it is not standard in GNOME by itself (it's not present in Fedora or Manjaro e.g.).

A quick fix is just replacing it:

![screenshot from 2018-07-07 16-36-53](https://user-images.githubusercontent.com/1725635/42411872-3dd066ca-8204-11e8-8adb-c763f9d7fa01.png)

**Comment by pjgoodall** [comment]
I now know a bit more, and am happy that a little, fairly normal keyboard configuration can solve the problem. Installation notes for Ubuntu?
