### ISSUE TITLE
The REPL should remember its last location

### ISSUE THREAD

**Issue by dwijnand** [idris-hackers/atom-language-idris#161]
I prefer to horizontally split my code and the REPL. Because I need to relaunch the REPL for it to pick up new changes, I'm suffering from the REPL always opening on a vertical split ignoring the fact that I move it to a vertical split.

**Comment by justjoheinz** [comment]
You should not need to restart the repl to pick up changes. Typechecking the file should be sufficient. Is this not the case?

**Comment by dwijnand** [comment]
Thank you - it would appear so. Didn't think to try that.

**Comment by dwijnand** [comment]
I'm not sure what the issues policy is in this project but I just wanted to point out that, despite my mistake as described in my last comment, I still think that the REPL should remember its last location - that is to say: I still think this issue is valid.

**Comment by justjoheinz** [comment]
Ok :-) I was probably a bit to eager
