### ISSUE TITLE
Syntax: ' in the end of string should not be highlighted as quote

### ISSUE THREAD

**Issue by Heather** [idris-hackers/atom-language-idris#18]
for example `index'` doesn't open quote but highlighting will fail on it

**Comment by archaeron** [comment]
@Heather thanks. can confirm the problem.
![quote_highlighting_before](https://cloud.githubusercontent.com/assets/471043/7846279/d6df0600-04bc-11e5-8240-bb89b81dcf7c.PNG)

**Comment by archaeron** [comment]
my unsuccessful try to fix it ;)
![quote_highlighting_wrong](https://cloud.githubusercontent.com/assets/471043/7846286/e5c2fbf4-04bc-11e5-8d33-229443855ef5.PNG)

**Comment by archaeron** [comment]
![quote_highlighting_after](https://cloud.githubusercontent.com/assets/471043/7871794/82af0a22-0592-11e5-98f5-ac0cc328416c.PNG)

**Comment by Heather** [comment]
:+1:
