### ISSUE TITLE
Reloading is much slower than the terminal REPL

### ISSUE THREAD

**Issue by samestep** [idris-hackers/atom-language-idris#180]
When I was just starting to use Idris, I used the REPL in the terminal and was satisfied enough with the speed. I quickly switched to using this Atom package instead, because of the advantages it gives over a plain terminal. However, I have been experiencing terrible performance using this package; it's a bit frustrating to press `ctrl-alt-a` or `ctrl-alt-c` or `ctrl-alt-l` and have to wait over a second before the desired change is applied.

Of course, some of this will be fixed if #127 is resolved, but the problem seems to be that reloading in and of itself is much slower than it should be. I did some fairly unscientific tests of this using the [hangman] example and an ordinary stopwatch, in which I either typed `:r`, hit enter, and timed how long it took for the REPL prompt to show up again; or hit `ctrl-alt-r` and timed how long it took for the text to change from "Idris: Typechecking..." to "Idris: File loaded successfully". Here are my results:

| Terminal | Atom  |
| -------- | ----- |
| 1.55s    | 7.17s |
| 1.55s    | 7.67s |
| 1.84s    | 6.67s |
| 1.63s    | 7.83s |
| 1.75s    | 8.01s |
| 1.54s    | 6.55s |
| 2.04s    | 7.37s |
| 1.56s    | 7.63s |
| 1.55s    | 9.05s |
| 1.74s    | 7.09s |

Is this expected? I haven't been able to find any existing references to this dramatic performance difference, so I don't know if it's a problem with this package or if it's just me. If the former, is this something that could be fixed?

[hangman]: https://github.com/idris-hackers/idris-demos/blob/356a5aa1dbd43f869b0eebd8b8fec15f790cc0dc/Hangman/Hangman.idr

**Comment by justjoheinz** [comment]
Of course the performance can be improved, but I guess you are comparing apples with bananas. If you are already inside the REPL a lot of work has already been done, what we are doing would be more comparable to building the package:

    time idris --build hang.ipkg

    real	0m5.234s
    user	0m4.950s
    sys	0m0.265s

But of course there are several ends which could be optimised, one is the idris compiler itself, and handling of compilation steps in atom. I for one prefer that atom always typechecks when I tell it to do so even if it takes awhile. But PRs are welcome!

**Comment by samestep** [comment]
I don't follow. I ran those `ctrl-alt-r` commands with the file open in my left pane while having the REPL open in my right pane (`ctrl-alt-enter`), and those are the times that I got. I can imagine one of two things being the case: either

- "typechecking" (`ctrl-alt-r`) does something fundamentally different from "reloading" (`:r`) or
- typechecking (`ctrl-alt-r`) doesn't use the running REPL process like reloading (`:r`) does.

If the former, what exactly is the difference between `ctrl-alt-r` and `:r`? I thought that those were the same thing. If the latter, then why doesn't typechecking use the running REPL process where, as you said, "a lot of the work has already been done"? Or is there something else going on here that I don't understand?

**Comment by justjoheinz** [comment]
I am by no means an expert with the internals of idris, but what we do is that typechecking is done via an internal command called `:load-file` with the repl being in `ide-mode`. When this is done, idris does a lot more than just type checking the file, it also parses it, and responds with a vast amount of information for the ide (some of which we cannot use unfortunately).

You can have a look at this comment in an idris issue which is closed due to lack of volunteers: 
https://github.com/idris-lang/Idris-dev/issues/1539#issuecomment-162701286

I will close the issue for the time being, as I can't see how we could significantly improve the process within atom at the moment.
