### ISSUE TITLE
Comment (|||) wrapping is broken

### ISSUE THREAD

**Issue by artagnon** [idris-hackers/atom-language-idris#181]
```
||| A line under 80 characters <M-q>
||| Another line to wrap
```

produces:

```
||| A line under 80 characters <M-q> ||| Another line to wrap
```

expected:

```
||| A line under 80 characters <M-q> Another line to wrap
```

This functionality (from atomic-emacs) works fine in other language modes.

**Comment by justjoheinz** [comment]
Which package are you using to wrap lines or comments? I cannot reproduce your steps.

Also what happens with other idris style comments:
`--` for single line comments and `{-` and `-}` for multiline comments?

My initial guess is that the package you are using does not recognize the first comment style from the grammar.

**Comment by artagnon** [comment]
The other two comment styles wrap fine. Oh, and it's alt-q, not C-q. How does atomic-emacs know that `--` is a comment?

```
alt-q | autoflow:reflow-selection | Atomic Emacs | atom-workspace atom-text-editor
```

**Comment by justjoheinz** [comment]
I had a look in the autoflow code, it does not care about the language settings, the comment characters are hardcoded.
https://github.com/atom/autoflow/blob/a8e89d4fe0d8c15babfa53df73263cc930882597/lib/autoflow.coffee#L52

You will need to add a feature or bug report to the autoflow package.

Th
