### ISSUE TITLE
Support a multi-line `pkgs` list in the .ipkg

### ISSUE THREAD

**Issue by artagnon** [idris-hackers/atom-language-idris#187]
#29 added support for specifying packages in `opts` as "-p contrib -p  config"; however, when attempting to specify packages using `pkgs`, atom-language-idris doesn't find the imports:

```
pkgs = effects
     , contrib
     , config
     , lightyear
     , containers
     , bytes
```

**Comment by justjoheinz** [comment]
Could you try to specify the packages in one line e.g.

pkgs = effects, contrib, config, ....

and report back if that works, please?

2017-08-21 17:07 GMT+02:00 Ramkumar Ramachandra <notifications@github.com>:

**Comment by artagnon** [comment]
Yes, that seems to work. It does, however, become impractical to put all of them on one line when there are many packages.
