### ISSUE TITLE
Atom tabulation settings are not respected for "ctrl+alt+w"

### ISSUE THREAD

**Issue by SamuraiJack** [idris-hackers/atom-language-idris#194]
When adding a "with" pattern, new lines appears in the source code with 2 spaces indentation (hardcoded somewhere?) even that tab length is set to 4 in my Atom.

```
myReverse : (input : List a) -> List a
myReverse input with (snocList input)
  myReverse [] | Empty = ?myReverse_rhs_rhs_1
  myReverse (xs ++ [x]) | (Snoc x y) = ?myReverse_rhs_rhs_2
```

**Comment by justjoheinz** [comment]
idris itself sends the text which is to be inserted. And idris can be configured to send different identations. See `idris --help` and specifically:

```
  --indent-with INDENT     Indentation to use with :makewith (default 2)
  --indent-clause INDENT   Indentation to use with :addclause (default 2)
```

atom does not yet support invoking the idris backend with configuration options for this. A PR is most welcome.

**Comment by SamuraiJack** [comment]
I see, thanks for the explanations. I'll try to do a PR once I'll finish the book.

**Comment by justjoheinz** [comment]
This has been fixed by https://github.com/idris-hackers/atom-language-idris/pull/209
