### ISSUE TITLE
Esc should close the panel

### ISSUE THREAD

**Issue by tobia** [idris-hackers/atom-language-idris#196]
As suggested in [this discussion](https://discuss.atom.io/t/idris-plugin-how-can-i-close-the-bottom-panel/50739/2?u=tobia), this plugin should listen for `core:cancel`, which is usually bound to Esc, and close the bottom panel.

Other temporary bottom panels do this, for instance the various find / replace ones.

[Here](https://github.com/atom/atom-select-list/blob/master/src/select-list-view.js#L74-L101) is an example of a component doing just that.

I will try to send a PR myself, if I can find my way around the codebase.

**Comment by justjoheinz** [comment]
PRs are very welcome! I did some contributions to the atom idris mode myself, so if you need any help, just post here, though I am by no means familiar with Atom/Coffeescript
