### ISSUE TITLE
Add keybinding for displaying holes

### ISSUE THREAD

**Issue by turion** [idris-hackers/atom-language-idris#197]
In the tutorial, it says erroneously that `ctrl-shift-p` is the keybinding for displaying holes. (Instead it does something else, which I don't understand at all.) There should be a simple keybinding for displaying holes.

**Comment by justjoheinz** [comment]
Currently Atom does not support displaying all holes via a key binding. To get all holes you can invoke the command palette (CTRL-shift-p) and type holes.

I can only guess, that you pressed ALT-shift-p which adds a proof clause as described here:
http://docs.idris-lang.org/en/latest/reference/misc.html#match-application

I close this for now, but please feel free to reopen in case ctrl-shift-p does not open the command palette for you.

**Comment by turion** [comment]
That was the thing I was doing wrong, thanks! I still think that there should be a key binding for displaying all holes (but well, I can add my own, I think).
