### ISSUE TITLE
Ensure that keybindings only work on Idris files

### ISSUE THREAD

**Issue by tcarlsen** [idris-hackers/atom-language-idris#2]
from your todo list:

> When Atom supports it, ensure that they only work in the grammar scopes that they should work in.

take a look at [atom-keymap-plus](https://github.com/tcarlsen/atom-keymap-plus), I use this in my plugins to make sure my commands only triggers in the specified files :wink: 

as you can see here all my packages have the same keybinding but only one is triggered based on the file type

![screenshot 2014-05-01 09 19 56](https://cloud.githubusercontent.com/assets/145288/2850543/2442aa00-d101-11e3-9ad4-0e7f6ac0defb.png)

**Comment by archaeron** [comment]
I've now made that the commands are at least only triggered in idris files, so that we don't interfere with other packages
