### ISSUE TITLE
Can't figure out how to install and use

### ISSUE THREAD

**Issue by david-christiansen** [idris-hackers/atom-language-idris#21]
I've been wanting to follow along in the development of this package, but I can't seem to figure it out. I'm completely new to Atom, so please take this in that spirit.

When I do "apm install", Atom doesn't seem to actually get a copy of the plugin. I've also tried symlinking the repo into `~/.atom/packages/language-idris`, but then it shows up as a very old version with a picture of @fangel's face, rather than showing the metadata in the JSON file in the repo.

I can get into a settings window and give it the path to Idris, but none of the keyboard shortcuts in the README seem to work - I certainly don't see anything happen, though I may just not know what to look for.

I don't know how much of this is my not knowing Atom, and how much is the plugin. However, this plugin does have the potential to be the "goto Idris interface" for people who aren't in to the classical editors, so it might be nice to have documentation on how to install it and set it up, and perhaps a short tutorial saying "paste in `add : Nat -> Nat -> Nat`, then do this to add a clause, then this to case split, then fill it out, then type check with this command". Another thing that's been nice in `idris-mode` for Emacs has been having a menu that lists the available commands, for those haven't yet learned keybindings.

I keep seeing tantalizing screenshots, but the package has, thus far, eluded me.

**Comment by Heather** [comment]
It will be also interesting for me, for now I put repository into `~/.atom/packages/language-idris` and run npm install there to get deps etc but I doubt if that is correct way

**Comment by david-christiansen** [comment]
Do I need to use `npm` instead of `apm`?

**Comment by archaeron** [comment]
hey @david-christiansen 
I'm glad that you have never used atom. We should find out what is hard to do and write that down :)
Are you trying to use the version from atom.io or a clone from this repo?

**Comment by archaeron** [comment]
if you use the version from atom.io (by going to the settings and then install) everything should be done for you and you should be good to go. If not it's a bug.

If you clone this repo you need to rename it to language-idris and then do a `apm install` from the package directory.

**Comment by archaeron** [comment]
I haven't had the opportunity to test it on Linux yet, so that's another thing I need to do. There could still be platform related bug. I think I fixed one yesterday but there could be more.

**Comment by archaeron** [comment]
@Heather @david-christiansen 
someone tested it for me on Linux. It's not working at all. I'm really sorry. I'll test it this evening on Linux myself and fix the errors.

**Comment by archaeron** [comment]
This https://github.com/idris-hackers/atom-language-idris/commit/c177eadb4b3a0472ed0b9b5c87c53d61aea4cd69 should have fixed the issue with the wrong icon being displayed.

I tested it on my linux installation now and it didn't work. So to find the error I restarted atom two or three times and now it's working as it should. I never changed anything. So at the moment I have no idea what is going wrong.

@david-christiansen I started a small tutorial. Did you think something like this? https://github.com/idris-hackers/atom-language-idris/commit/15cce4c3477ec769b2d24cbf2b809591ba50685d

**Comment by david-christiansen** [comment]
That's definitely a good start! I posted a couple minor copyediting comments - hope that's OK :) I'll give it a try again,

The tutorial/README should probably note that the name of the directory on disk is significant - I hadn't realized that.

**Comment by archaeron** [comment]
Thank you, I fixed both mistakes.

I'm not sure what you mean with:

> the name of the directory on disk is significant

Do you mean the name of the `language-idris` folder? You shouldn't have to change that name if you install it normally via the atom settings.

**Comment by david-christiansen** [comment]
Yeah, but if I want to hack on it, I need to be able to install it from
source! :-)

**Comment by archaeron** [comment]
ah, sorry. Yes it's true that you have to rename the folder, but that is explained here: https://github.com/idris-hackers/atom-language-idris#development
 :)
(or at least I tried to, but it could still be unclear)

**Comment by archaeron** [comment]
Ah. there is a mistake on `master` at the moment that I fixed in the new `documentation` branch. The folder needs to be called `language-idris` and not `language-atom`.

**Comment by david-christiansen** [comment]
I've now followed the instructions to install it from the central repository, and `Ctrl-Alt-T` works on `Nat`. But I can't figure out how to type check the file so that I can read docs or get types for my own code - I don't see a "load current file" command in the command palette, for instance.

When I close the file and re-open it, the Idris commands stop working even for built-in names. What am I doing wrong?

**Comment by archaeron** [comment]
it should typecheck the file on save. There should be a tiny message in the bottom statusbar. I should improve that. Messages should be clear.
If `Ctrl-Alt-T` works should `Ctrl-Alt-D`work too.

it's so hard to find the error when it's working for me, I'm really sorry for this :(

**Comment by archaeron** [comment]
here is a screenshot of how the package should show errors that the compiler is reporting
![idris_errors](https://cloud.githubusercontent.com/assets/471043/7972294/9af6d1a6-0a4b-11e5-8697-118be7432621.PNG)

**Comment by david-christiansen** [comment]
I'd consider this issue to be closed if the docs that have been posted in comments here were moved into the actual docs :)

**Comment by archaeron** [comment]
I think all the things are documented somewhere :)

here it says how to install it as a normal user:
https://github.com/idris-hackers/atom-language-idris#usage
explained again in the tutorial:
https://github.com/idris-hackers/atom-language-idris/blob/master/documentation/tutorial.md#installation

here is an explanation for the development of the package:
https://github.com/idris-hackers/atom-language-idris#development

and the tutorial explains things like "type info" and "show documentation".
https://github.com/idris-hackers/atom-language-idris/blob/master/documentation/tutorial.md#type-info
https://github.com/idris-hackers/atom-language-idris/blob/master/documentation/tutorial.md#show-documentation

there is one thing missing as far as I can see and that is the explanation of how to use the metavariables and proof search. I've opened an issue for that here:
https://github.com/idris-hackers/atom-language-idris/issues/24

**Comment by david-christiansen** [comment]
Cool! Hope I make it work soon!
