### ISSUE TITLE
Release 0.5.0

### ISSUE THREAD

**Issue by justjoheinz** [idris-hackers/atom-language-idris#215]
@melted I am done with all fixes I can do at the moment. I think we should go ahead with a release. Is there anything I can do to support this?

**Comment by melted** [comment]
You’ve done enough. :)

All I have to is to set a tag, collect some release notes and publish it.

**Comment by melted** [comment]
Oh yeah, and we should decide whether to put in the updated keybindings...

Should we? I like them, but they conflict with the book.

**Comment by melted** [comment]
Published!
