### ISSUE TITLE
Idris 1.3.1 compile crashes, then node throws a type error exception

### ISSUE THREAD

**Issue by Phiroc** [idris-hackers/atom-language-idris#230]
Hello,
when I ctrl-alt-R my code in Atom, a message appears stating that the Idris compiler crashed. When I run the command again, I get the following message:

> Uncaught TypeError: Cannot read property 'length' of undefined
> /Users/philippe/.atom/packages/language-idris/node_modules/rx-lite/rx.lite.js:78
> Show Stack Trace
> The error was thrown from the language-idris package. This issue has already been reported.
> View Issue

I am using the 0.5.0 language-idris package in Atom 1.36.1 on MacOSX Mojave 10.14.4.

Best regards,

**Comment by justjoheinz** [comment]
Most likely fixed with the 0.5.1 release
