### ISSUE TITLE
Can't case-split or check hole type, but can type check whole file

### ISSUE THREAD

**Issue by corazza** [idris-hackers/atom-language-idris#231]
Ctrl+Alt+R works normally, as does "make case", but I cannot Ctrl+Alt+T holes or Ctrl+Alt+C case pattern variables. For holes the error is "No such variable", and for case-splits it's "not a pattern variable".

I'm on Windows, Idris is installed through msys2 but can be ran in cmd if that matters. I've recently re-installed Idris (now I'm on v1.3.1, couldn't get something to work in v1.3.2) after which this started happening. The path setting in the package seems to be correct as well.

**Comment by justjoheinz** [comment]
Hi @corazza - sorry, I just noticed the issue. Can you provide a small example idris file? Could you get idris 1.3.2 to work meanwhile?

**Comment by corazza** [comment]
Hey I'm sorry I totally forgot about this. I'm pretty sure it's been fixed. I also missed your followup question:(
