### ISSUE TITLE
Add an entry for proving to the tutorial

### ISSUE THREAD

**Issue by archaeron** [idris-hackers/atom-language-idris#24]

**Comment by archaeron** [comment]
there is a start here:
https://github.com/idris-hackers/atom-language-idris/blob/663c2db75a72dbd0f98f880831bffdb91f459e46/documentation/tutorial.md#proving

if someone who knows more about Idris than me could take a look at it I'd be grateful.

**Comment by david-christiansen** [comment]
I haven't yet gotten the Atom mode to work, so I can't say whether that part is right, but the general process seems perfectly reasonable and clearly described.

**Comment by archaeron** [comment]
thanks :)

**Comment by archaeron** [comment]
a finished and update version is now in the branch that will become the new version. I'm closing this issue in favour of focused issues.
