### ISSUE TITLE
Typechecking doesn't check for totality?

### ISSUE THREAD

**Issue by joliss** [idris-hackers/atom-language-idris#240]
The following file gets rejected correctly when I call `idris` directly, but passes when I use the "Typecheck" command in Atom.

```
$ cat total.idr
total empty : Void
empty = empty
$ idris --check total.idr
/Users/primary/src/idris-learning/total.idr:2:1-13:
  |
2 | empty = empty
  | ~~~~~~~~~~~~~
Main.empty is possibly not total due to recursive path Main.empty
```

![typecheck](https://user-images.githubusercontent.com/524783/72277987-eb27c580-362a-11ea-884d-20a0f8465279.gif)

Am I doing something wrong, or misunderstanding what "Typecheck" is supposed to do? Or could this be a bug in the language-idris package?

I'm using language-idris 0.5.1 on Atom 1.42.0 with Idris 1.3.2.

**Comment by justjoheinz** [comment]
No, this is as it is at the moment AFAIK. idris doesn't flag these totality errors as errors when in IDE mode. I do not know the rationale behind this to be honest. You can still check for totality by invoking the documentation of the function.
