### ISSUE TITLE
Create release 0.5.2

### ISSUE THREAD

**Issue by justjoheinz** [idris-hackers/atom-language-idris#244]
@melted - not a lot of fixes, but at least some.
Please create a release. Thank you.

**Comment by melted** [comment]
I don't have the stuff on this work computer, so it could take a while. But you can do it instead, you have the rights to do it, just run `apm publish minor` (or by specifying the version tag if you want to push that manually). https://flight-manual.atom.io/hacking-atom/sections/publishing/

**Comment by justjoheinz** [comment]
Oh, cool. I did not know that it was this easy. I just published 0.6.0 by accident, but nevermind :-)

**Comment by melted** [comment]
Right, the last digit is `patch`
