### ISSUE TITLE
TypeScript rewrite

### ISSUE THREAD

**Issue by archaeron** [idris-hackers/atom-language-idris#247]
Hi @melted @justjoheinz 

I looked at the CoffeeScript codebase I wrote a long time ago and the quality of the code is not very good.

I thought I could port it to TypeScript hoping that it would be much easier to change and to find bugs. It would also make it easier to switch to other typed languages later on.

Would you be interested in that?

**Comment by melted** [comment]
I wonder if the compiled javascript from coffescript is human-friendly enough to use as the starting point.

**Comment by archaeron** [comment]
the main problem is that the current code is a bit of a mess. I tried to run it through
https://github.com/decaffeinate/decaffeinate which is an okay starting point, but since CoffeeScript isn't typed, lots of functions take weird arguments.
I've also already found places where null checks should be placed.
It's totally doable, it just needs a bit of time :) I'd be willing to convert it and I believe it would make the job of fixing bugs and maintaining the package easier. What do you think?

**Comment by melted** [comment]
I think it's a good idea. I'm not fond of coffeescript.

**Comment by archaeron** [comment]
Neither am I :)
But it was the best option at the time. And integrated into atom. 

I will ping you when I have an initial working version.

**Comment by justjoheinz** [comment]
Should we not concentrate on one entry level idris mode, e.g. via vscode which seems to be getting contextual syntax highlighting as well? The past years I had been more or less the only contributor to the atom mode, and my interest in idris waned a bit to be honest, since it is so hard to adopt libraries for it.

**Comment by archaeron** [comment]
my plan was to convert this to typescript as a first step.
Then convert that to a LSP server. So that we can have one backend for Atom and VS Code.
Converting the current implementation to a good LSP implementation is really hard, because the CoffeeScript code is quite a big mess.

What do you mean by "adopt libraries for it"?

**Comment by justjoheinz** [comment]
@archaeron I just wanted to say, that I do not find it trivial to write an idris connection to say a "C" library etc.

**Comment by archaeron** [comment]
@justjoheinz I've never tried that. Do you mean it's hard to get them to work together or that it's hard to convert an imperatiave interface to a functional one?

@melted and @justjoheinz I have an initial translation into TypeScript. I'd say it's already more comfortable to work with even though there are still lots of `any` types.
Do you know if it's possible to release beta updated for atom packages?
Could you take a look at it and tell me what you think? Would you prefer to merge this soon rather than later and remove the `any`s after?

**Comment by justjoheinz** [comment]
Can you push your branch to the main github repo. I had a quick look, and it looks promising. I wouldn't mind working on this together.  I also would like to experiment a bit with the local development version.

Regarding the libraries - what I wanted to say is that in order to fool around with Idris to understand dependent types and its implications it is brilliant, but adopting 3rd party libraries is not something easy (for me). I want to learn Idris (not C or any other backend language).

**Comment by melted** [comment]
I think Idris 2 helps a lot, it's far less unwieldy than Idris 1 and the fact that it's written in Idris will help clear away pain points, the compiler serves as a huge benchmark and example. And functionality implemented to help the compiler can be moved to the libs and be useful for other programs.

**Comment by archaeron** [comment]
@justjoheinz I will push it to the main repo in a sec
I understand the lack of libraries can be frustrating. They will just need time :(
But I'm hoping by providing a good editor plugin we can help people write libraries.

@melted that means we should make this work with idris2 :)

**Comment by archaeron** [comment]
I have opened a "work in progress" pull request: #248

**Comment by archaeron** [comment]
seems like we should be using this to transpile the packages to JS: https://github.com/smhxx/atom-ts-transpiler

From the FAQ:

> Can't I just transpile my package myself?
> Yes, absolutely. In fact, this package is written in TypeScript and transpiled prior to publishing. However, it's a bit more complicated for Atom packages than for NPM packages, since Atom packages are hosted directly from their GitHub repo, rather than uploaded to an external package repository like npm. Users download your package exactly as it exists on your master branch, so if you want your code to be transpiled prior to distribution, you'll have to actually commit the transpiled output to the repo (e.g. by setting up a pre-commit hook to run tsc,) and the user will end up downloading both the TypeScript and JavaScript versions, anyway. With a custom transpiler, all that mess can be avoided. The transpilation of your TypeScript code is handled automatically by Atom itself, with zero performance penalty after the first time the package is installed and run.

**Comment by archaeron** [comment]
@melted @justjoheinz I'm sorry to bother you, but how do we want to proceed? The PR should be ready to take a look at it.
It seems to work in my relatively limited tests. The question now is if we would want to merge this soonish, or still polish it more
and merge it later? With the danger that fixes in the CoffeeScript would have to be backported.

**Comment by melted** [comment]
I'll try to run it, so it has been tried on more than your computer. :-)

I would prefer to put it in quickly. I want to get in a little Idris 2 polish before making a new release, and it would be better to make that in Typescript.

**Comment by justjoheinz** [comment]
I tried to have a quick look :cannot find atom-ts-transpiler is what I get
when starting the convert-to-typescript-2 branch (atom -d . ) . I am bit
busy at the moment workwise - do I need to install dependencies myself,
when in dev mode?

Am Di., 9. Juni 2020 um 14:17 Uhr schrieb Niklas Larsson <
notifications@github.com>:

**Comment by justjoheinz** [comment]
Ah, I see - npm install in the project dir helps. Looks good to me. My little typechecking notification disappeared, but other than that, I see no biggies. Go ahead and merge.

**Comment by archaeron** [comment]
@justjoheinz as far as I know in dev mode you need to use `npm install` yourself and it should happen automatically when a user installs it via the store

ok, I'll merge it in.
