### ISSUE TITLE
Metavariables should maybe save the file or the new variables wont be shown

### ISSUE THREAD

**Issue by archaeron** [idris-hackers/atom-language-idris#25]
@david-christiansen how do you handle this in the emacs-mode? The ide-mode needs a saved file to analyze it. When I edit a file and then show the metavarables they will still be the same ones as last time you saved the file. Is it okay for me to just overwrite the file for the user?

I hope the question is clear :)

**Comment by david-christiansen** [comment]
The Emacs mode separates saving from type checking. Basically, an Idris buffer can be in three states: not loaded, fully loaded, and partially loaded. At most one buffer can be in one of the loaded states at any given time. Asking Idris to type check is a separate command from saving. Type checking implies saving, and most interactive editing commands (e.g. case split or add clause) imply type checking.

The metavariable list is shown from the compiler's current state, whatever that might be. It doesn't modify the buffer state at all. This seems to work fairly well in practice. If a setting is enabled, the metavariable list is also triggered on type checking if there are metavars.

Is this a reasonable answer? Am I missing something?

**Comment by archaeron** [comment]
Very reasonable answer actually, thank you very much. :)

It's probably best to divide it too. And maybe add an option to typecheck on save. I'll have to think about this.

**Comment by david-christiansen** [comment]
In practice, I often want to save without type checking, because sometimes type checking is quite slow for very large files with complicated computation happening in the types.

**Comment by archaeron** [comment]
absolutely, you're right. I never got even close to that point, so I haven't thought about it :)
I'll split saving and typechecking.

I should make a roadmap for the package.

**Comment by david-christiansen** [comment]
Or you can do what I do and hack randomly and hope it becomes useful for
someone else!

**Comment by archaeron** [comment]
If you are an indication, everyone should hack randomly :D

I should have some time for this tomorrow.

**Comment by archaeron** [comment]
ok, I have a first try here: https://github.com/idris-hackers/atom-language-idris/compare/optional-typecheck?expand=1

at the moment you have to invoke the typechecking by hand though. There is no option yet to do it automatically.

**Comment by archaeron** [comment]
this is the same as #34.
The new version will save the file and typecheck it before applying changes to the code but you have to manually typecheck before showing information about types, holes, ...
