### ISSUE TITLE
Disable invoking the compiler (optionally)

### ISSUE THREAD

**Issue by alexchandel** [idris-hackers/atom-language-idris#27]
Please add an option to disable this. It lags out my editing, it currently is crashing every time I open an Idris file, and sometimes all I really want is syntax highlighting. Simply not setting the path to idris isn't good enough, since Atom warns me every time I open it to set the path.

**Comment by david-christiansen** [comment]
I agree - in the Emacs mode, you need to invoke the type checker explicitly, because it can sometimes be quite slow. Auto-typecheck-on-save is a nice option, but in my opinion it shouldn't be the default.

**Comment by archaeron** [comment]
sorry. I'm working on that. But My exams start on Monday and I don't have a lot of time at the moment.
Ill have time in aabout two weeks.

**Comment by archaeron** [comment]
I might have a working version of this by tonight. But no guarantees.

**Comment by alexchandel** [comment]
*holds out hope*

and wow, your exams are so late!

**Comment by archaeron** [comment]
sorry, no luck :(

But I'm on it. I realized that it is probably a larger change, And I'll need to consider things like #28.

Doesn't every country have its own time for the exams? Even the Universities in my vicinity all have different dates.

**Comment by archaeron** [comment]
there is a step in this direction here: https://github.com/idris-hackers/atom-language-idris/compare/optional-typecheck?expand=1
but it will take some time to finish

**Comment by archaeron** [comment]
the compiler is only started when you use one of the commands that actually need it.
https://github.com/idris-hackers/atom-language-idris/commit/22f4ddbbc24235e8fdceb61ac231b8da2306f5b7
