### ISSUE TITLE
Add a means of setting the Idris -p option

### ISSUE THREAD

**Issue by david-christiansen** [idris-hackers/atom-language-idris#29]
Idris has a global library installation directory which is divided into packages. The `prelude` and `base` packages are always available for import, but further packages need to be enabled by passing Idris the `-p PKGNAME` command-line option.

This is something that's project-specific, so it doesn't really make sense in the global Idris configuration area (though that can be a temporary stopgap).

In the Emacs mode, we set this option in two ways:

1. We check if the user has set an Emacs file variable to a list of packages, and use them if so. File variables allow an Emacs Lisp variable to have a particular value when editing a particular file, and the value is stored in a specially-formatted comment. I'm not sure if Atom has a similar feature or not.
 
2. If the file being edited is in a directory that contains a `.ipkg` file, or a subdirectory of such a directory, that file is processed to find the list of packages that a command-line invocation of `idris` would get from the package commands (e.g. `--build`, `--install`). These are then passed to the Idris subprocess.

I don't know the right solution for Atom, but it's pretty important to be able to do this.

**Comment by david-christiansen** [comment]
Probably we should set up Idris to (a) find the .ipkg file, if one exists, and (b) report back the contents of its fields, rather than re-implementing all this in every editor...

**Comment by archaeron** [comment]
I support this idea :D

In the interim I we could just search for an ipkg file in the open directory and use that one without recursing through higher directories.
I'm pretty sure atom doesn't have file variables, so that option is out.

Would we have to parse the ipkg file, search for the `opts` opts and pass them to the compiler?
e.g.:

```
package highlighter

sourcedir = src
modules = SExpParse, Main
executable = highlighter
main = Main
opts = "-p lightyear --typeintype"
```
would result in

`idris --ide-mode -p lightyear --typeintype SExpParse.idr`

**Comment by david-christiansen** [comment]
> In the interim I we could just search for an ipkg file in the open
> directory and use that one without recursing through higher directories.
>
This will only work for the simplest Idris programs - anything with a
hierarchical namespace will fail mysteriously. I don't think that's likely
to be so useful.


> I'm pretty sure atom doesn't have file variables, so that option is out.
>
OK

> Would we have to parse the ipkg file, search for the opts opts and pass
> them to the compiler?
> e.g.:
>
> package highlighter
>
> sourcedir = src
> modules = SExpParse, Main
> executable = highlighter
> main = Main
> opts = "-p lightyear --typeintype"
>
> would result in
>
> idris --ide-mode -p lightyear --typeintype SExpParse.idr
>
>
> That's what idris-mode does.

/D

**Comment by archaeron** [comment]
> This will only work for the simplest Idris programs - anything with a
hierarchical namespace will fail mysteriously. I don't think that's likely
to be so useful.

When I open for instance https://github.com/archaeron/highlighter my project looks like this
![highlighter_file_structure](https://cloud.githubusercontent.com/assets/471043/8857953/0c33534e-3175-11e5-9273-c1fa82e7d35d.PNG)

so even if the ipkg file and the source files are not in the same directory it would work.

If on the other hand I'd just open the source folder it wouldn't.

But at least you'd see what ipcg file it would use.

**Comment by archaeron** [comment]
or is this one of the simple idris programs you where talking about? :)

**Comment by david-christiansen** [comment]
I hadn't realized that Atom had a notion of "current open directory" that was different from the directory that the file is in. This should work fine, then!

**Comment by archaeron** [comment]
perfect, thanks for the answer :+1:

**Comment by david-christiansen** [comment]
:-)

**Comment by NobbZ** [comment]
Is there some workaround to get `-p` support until 0.3.0 gets released? I try to play around with `effects` and so this plugin does only provide nice colors but nothing else… Nearly all idris related functionality is cancelled with “can't find import Effects/<Stuff>”.

**Comment by archaeron** [comment]
there is a branch where there is some rudimentary ipkg support.
it's working for me, but I haven't tested it too much. So you could clone the repo to your packages folder and checkout the `ipkg` branch

**Comment by NobbZ** [comment]
Will I get any update notifications when I switch over or do I need to pull
regularly then?

archaeron <notifications@github.com> schrieb am Mo., 17.08.2015, 20:22:

**Comment by archaeron** [comment]
When I'm working on a feature branch that has not yet the newest version in the config file it tells me that there is a newer version available. But I've never tried updating then trough the official channel.

**Comment by NobbZ** [comment]
I just tried, but failed misserably:

1. deleted old `language-idris` folder from `~/.atom/packages/language-idris`
2. `git clone`d to `~/.atom/packages/language-idris`
3. `cd`ed to `~/.atom/packages/language-idris`
4. `git checkout origin/ipkg`.
5. start atom and get stacktrace (I get this also when using one of the released tags, while deleting and reinstalling via package maneger does not have the error):

**Atom Version**: 1.0.7
**System**: Ubuntu 14.04.3
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package, v0.2.4


### Stack Trace

Failed to load the language-idris package

```
At Cannot find module 'atom-message-panel'

Error: Cannot find module 'atom-message-panel'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/home/norbert/.atom/packages/language-idris/lib/idris-controller.coffee:5:10)
    at Object.<anonymous> (/home/norbert/.atom/packages/language-idris/lib/idris-controller.coffee:479:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (/usr/share/atom/resources/app.asar/node_modules/coffee-cash/lib/coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-material-syntax"
    ]
  },
  "language-idris": {}
}
```

### Installed Packages

```coffee
# User
atom-material-syntax, v0.2.3
atom-message-panel-service, v0.0.1-1
autocomplete-elixir, v1.3.12
autocomplete-erlang, v1.1.1
autocomplete-haskell, v0.4.5
haskell-ghc-mod, v0.8.9
ide-haskell, v0.7.1
language-idris, v0.2.4
linter-erlang, v0.2.0
racer, v0.17.1

# Dev
No dev packages
```

**Comment by archaeron** [comment]
this is now in v0.3.0
