### ISSUE TITLE
Program not loaded before running interactive editing commands

### ISSUE THREAD

**Issue by david-christiansen** [idris-hackers/atom-language-idris#34]
If I run the Add Clause command, I need to manually save the file before I can case split the resulting pattern variables, because otherwise, Idris hasn't re-typechecked.

In the Emacs mode, we check to see if the file has been modified since the last time it was type checked, and then invoke the type checker prior to running interactive editing commands. It might be good to do the same in Atom.

**Comment by edwinb** [comment]
I think it's a bit more than "might be good", because if it doesn't save and then you do an interactive command which happens to work, then the file can end up in a bad state. For example, starting with:

```
vZipWith : (a -> b -> c) -> Vect n a -> Vect n b -> Vect n c
vZipWith f [] ys = ?vZipWith_rhs_1
vZipWith f (x :: xs) ys = ?vZipWith_rhs_2
```

Case split on the first `ys`, then case split on the second `ys` without saving, and you get:

```
vZipWith : (a -> b -> c) -> Vect n a -> Vect n b -> Vect n c
vZipWith f [] [] = ?vZipWith_rhs_3
vZipWith f (x :: xs) (y :: ys) = ?vZipWith_rhs_3
```

The problem goes away if you always save before the split.

**Comment by david-christiansen** [comment]
Good point, @edwinb.

**Comment by archaeron** [comment]
Hello

this is a good point.
In the new version that I have on the "optional-typecheck" branch I typecheck the code before splitting. And typechecking inplies saving the file. I removed the auto-typecheck-on-save for now.

https://github.com/idris-hackers/atom-language-idris/compare/optional-typecheck#diff-e875356097b1d027706a2fa01ee6e6cbR114

The same thing happens for all of the "higher" level commands. They all do a typecheck first. What do you think?

**Comment by david-christiansen** [comment]
In the Emacs mode, we don't type check before a hole list command, because people may want to see the holes again without waiting on the type checker (metavariables were just renamed holes, in case this seems confusing). Basically, things that change the code type check if the file is modified since last type check, and things that just look up information don't. This may be the wrong way, though - what do you think?

**Comment by archaeron** [comment]
I think this makes sense.
I've never worked on an Idris codebase longer than a few lines of code so I never had to wait, so I'm glad you're telling me this.
Do you have a way of indicating to the user in what state the editor is?

So you save (and typecheck) before `case-split`, `add-clause`, `add-proof-clause`, `add-missing`, `make-with` and `proof-search`.?

And use the state of the last typecheck for `type-of`, `docs-for`, `metavariables`, ...?

**Comment by david-christiansen** [comment]
> Do you have a way of indicating to the user in what state the editor is?

There's a little indicator at the bottom of the screen in Emacs that says what language mode the editor is in. When the file has been type checked, it says `Idris (Loaded)`. When the file is first opened, or if it is modified after having been type checked, then it says `Idris (Not loaded)`. Also, because it's possible to only type check part of the file (which can be nice when making changes at the beginning of the file), there's an option to get a different background color on the part of the file that's successfully type checked. Finally, the semantic highlights are only applied to type checked code, so all the pretty colors are also an indicator, though they persist even when the file has been modified because the alternative was too jarring.

> So you save (and typecheck) before case-split, add-clause, add-proof-clause, add-missing, make-with 
> and proof-search.?
> And use the state of the last typecheck for type-of, docs-for, metavariables, ...?

Yes. You can [consult the source](https://github.com/idris-hackers/idris-mode/blob/master/idris-commands.el) if you're in doubt about a particular command. If the command includes a call to `idris-load-file-sync`, then it saves type checks the buffer. Let me know if there's any elisp that you can't figure out.

**Comment by archaeron** [comment]
I made a pullrequest for the branch that implements these changes, so that it's easier to see what I'm planning at the moment and so that it's possible to change the current direction of things if someone does not agree with it.
https://github.com/idris-hackers/atom-language-idris/pull/35

**Comment by archaeron** [comment]
this is done on the branch that will become the new version

https://github.com/idris-hackers/atom-language-idris/commit/885df5b5c6fb1172abe5dd63a83e9cdea8915325

**Comment by edwinb** [comment]
I'm still getting the behaviour I described above, with the latest Atom and the latest Idris mode (0.2.0). Have I done something wrong installing it? Do I need to make sure to delete things first?
