### ISSUE TITLE
Broken on Windows?

### ISSUE THREAD

**Issue by PhilAndrew** [idris-hackers/atom-language-idris#36]
Hi, I'm on Windows. Every time it starts up it asks me to set the path to Idris.

I set the path in the settings AND in the PATH environment variable but it still keeps asking to me to set the path.

I am using the Idris pre complied for Windows downloaded from here https://github.com/idris-lang/Idris-dev/wiki/Windows-Binaries for Windows 64 bit.

**Comment by Heather** [comment]
basically maybe it's something wrong with this place https://github.com/idris-hackers/atom-language-idris/blob/master/lib/language-idris.coffee#L15 but I don't have such error now... try to set variable there just to `'idris'` and see if it's related

**Comment by archaeron** [comment]
Hello @PhilAndrew 
I'm sorry for this. I'm working on a new version that handles things differently and doesn't check on startup if it finds idris.

Nevertheless it's strange that it can't find it. Did you install the package from the settings?

**Comment by PhilAndrew** [comment]
Am I supposed to out the path to the executable or the path in which the executable resides?

**Comment by archaeron** [comment]
The path to the executable (`idris.exe` on windows). Sorry, I should clarify that in the settings.

**Comment by archaeron** [comment]
It now says "Path to the idris executable" on the setting.

Is it working now for you?

**Comment by NightRa** [comment]
I'm on Windows and it works fine.

**Comment by archaeron** [comment]
:+1: works for me too on windows
