### ISSUE TITLE
The Idris Errors panel should tell me if typechecking went successfully

### ISSUE THREAD

**Issue by NightRa** [idris-hackers/atom-language-idris#43]
If I do typecheck and it fails, it raises the Idris Errors panel.
If I fix everything, typecheck again and it succeeds, currently there is no response what-so-ever and the old type error is still present.
I think there should be some indication that typechecking succeeded, and the old type error should not be displayed anymore.

**Comment by archaeron** [comment]
hello
tthere is a PR for this. :)
https://github.com/idris-hackers/atom-language-idris/pull/40

need to check something and then I can merge it

**Comment by archaeron** [comment]
this is now in master and is ready for the next version
https://github.com/idris-hackers/atom-language-idris/commit/d2b6a8649da07c1307e7b80443444cf9969b01ed

thanks to @edwinb for this
