### ISSUE TITLE
Save before executing idris commands

### ISSUE THREAD

**Issue by NightRa** [idris-hackers/atom-language-idris#44]
I suppose this is a design decision.
Currently, it queries idris with the last saved version of the file.
- I don't see where this would be preferred over querying over the current content that's visible on the screen.  
Therefore, I believe that there should be an automatic save before executing commands.

**Comment by archaeron** [comment]
hey
thanks a lot for opening this issues. things like these are important :)

there is another PR that does this here:
https://github.com/idris-hackers/atom-language-idris/pull/38

the same thing applies here as in the last issue.
will be in the next version. I'm leaving the issues open until it's fixed.

**Comment by archaeron** [comment]
this is now in master and is ready for the next version
https://github.com/idris-hackers/atom-language-idris/commit/39448cdb37ca157b69ab184e89a6c92ad0e9114c

thanks to @edwinb for this
