### ISSUE TITLE
Save before command isn't working properly.

### ISSUE THREAD

**Issue by NightRa** [idris-hackers/atom-language-idris#50]
I'm on v2.3.
Case splitting on one argument and then on another overrides the previous change - the command seems to work on the previous state of the text file.

Video:
http://screencast.com/t/2DW8pYMjBb

**Comment by archaeron** [comment]
Would it be possible for you to upload the file to a gist so that I can test it out?

**Comment by NightRa** [comment]
@archaeron https://gist.github.com/NightRa/c38bfdd6d019a64d42ab

**Comment by archaeron** [comment]
thanks a lot! and for the video too

**Comment by archaeron** [comment]
interestingly when I do the exact same thing, down to where I position the cursor I got a different behaviour.

my line looks like this in the end:
`prop2 Atom     Atom Refl Refl = ?prop2_rhs_4`

maybe this commit influecnes the behaviour?
https://github.com/idris-hackers/atom-language-idris/commit/e5e0593229af5f67fec1a1d6452933405c8a39df

**Comment by NightRa** [comment]
Again, can't reproduce anymore.
Next time I'll try to restart my computer and everything to try to avoid such temporal behavior again.

**Comment by archaeron** [comment]
This is a common issue for me with Atom.
Many times random things happen.

Did you restart Atom after the update to the new package? Maybe it still used the old code if not.

**Comment by NightRa** [comment]
I did restart Atom after the update and it behaved the same.
The next day the issue disappeared..

2015-08-10 12:37 GMT+03:00 archaeron <notifications@github.com>:

**Comment by archaeron** [comment]
Well I'm glad it's gone :D

But I'm a bit scared about what happend :P

Thanks for your help!
