### ISSUE TITLE
Status message should appear only in idris projects

### ISSUE THREAD

**Issue by laughedelic** [idris-hackers/atom-language-idris#52]
When I open whatever project not related to idris, I see the message `Idris (Not loaded)` in the status bar, which doesn't make any sense in this context:
<img width="175" alt="screen shot 2015-08-12 at 11 51 23" src="https://cloud.githubusercontent.com/assets/766656/9221227/d7f6c38a-40e8-11e5-98d7-461cbc2e8124.png">

**Comment by archaeron** [comment]
You're right, thanks for opening the issue.

**Comment by jeremy-w** [comment]
A start to fixing this:

```coffescript
  consumeStatusBar: (statusBar) ->
    atom.workspace.onDidChangeActivePaneItem (paneItem) ->
      console.log("active pane item is:", paneItem)
      /* (jws/2015-08-28)TODO: add/remove status based on if it is/not an Idris file */
    @controller.attachStatusIndicator statusBar
```
