### ISSUE TITLE
importing modules from the same directory in idris mode for atom fails

### ISSUE THREAD

**Issue by jeremy-w** [idris-hackers/atom-language-idris#57]
Reported by davidwlewis on IRC:

(00:18:44) davidwlewis: I'm having trouble importing modules from the same directory in idris mode for atom
(00:19:44) davidwlewis: I even hacked the way atom spawns the ide-mode process to add the project directory with the -i flag, no joy
(00:36:55) davidwlewis: Is this a limitation of ide-mode or is something busted at my end?
(00:55:34) christiansen` is now known as christiansen
(01:01:57) christiansen: davidwlewis: my guess is that the atom mode isn't setting the right working directory baed on the ipkg file
(01:02:04) christiansen: this is worth an issue there

**Comment by archaeron** [comment]
There is a branch I'm working on, that reads the ipkg file.

https://github.com/idris-hackers/atom-language-idris/pull/48

It's not yet ready for production though, sorry :(

**Comment by archaeron** [comment]
I fixed the [bug](https://github.com/idris-hackers/atom-language-idris/commit/1733375c942af78d8165ac99d142fcf7704e98c5) I had in that branch and it would be great to have testers for it
