### ISSUE TITLE
Uncaught Error: write EPIPE

### ISSUE THREAD

**Issue by Jmots2** [idris-hackers/atom-language-idris#64]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Microsoft Windows 10 Pro
**Thrown From**: [language-idris](https://github.com/idris-hackers/atom-language-idris) package, v0.2.4
### Stack Trace

Uncaught Error: write EPIPE

```
At events.js:141

Error: write EPIPE
    at exports._errnoException (util.js:734:11)
    at Socket._writeGeneric (net.js:668:26)
    at Socket._write (net.js:687:8)
    at doWrite (_stream_writable.js:295:12)
    at writeOrBuffer (_stream_writable.js:282:5)
    at Socket.Writable.write (_stream_writable.js:210:11)
    at Socket.write (net.js:612:40)
    at IdrisIdeMode.send (C:\Users\J\.atom\packages\language-idris\lib\idris-ide-mode.coffee:24:20)
    at IdrisModel.prepareCommand (C:\Users\J\.atom\packages\language-idris\lib\idris-model.coffee:64:16)
    at IdrisModel.load (C:\Users\J\.atom\packages\language-idris\lib\idris-model.coffee:68:6)
```
### Commands

```
  2x -3:11.9.0 editor:newline (atom-text-editor.editor.is-focused)
  5x -2:44.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:37.3.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:35.7.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -1:34 editor:newline (atom-text-editor.editor.is-focused)
     -1:09.3.0 language-idris:typecheck (atom-text-editor.editor.is-focused)
     -0:34.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.2.0 language-idris:typecheck (atom-text-editor.editor.is-focused)
```
### Config

``` json
{}
```
### Installed Packages

``` coffee
# User
language-idris, v0.2.4

# Dev
No dev packages
```

**Comment by Jmots2** [comment]
trouble connecting Atom to Idris REPL

**Comment by archaeron** [comment]
do you have `idris` in your path?

**Comment by razvan-panda** [comment]
Had the same issue and what fixed it for me was updating Atom to latest version.

**Comment by archaeron** [comment]
@razvan-panda thanks for the info :)

**Comment by Niriel** [comment]
> do you have idris in your path?
How do I do that?  Are we talking about Windows' $PATH, or some package option, or an Atom-level option?

**Comment by archaeron** [comment]
you can either add it to your windows `$PATH` or in the package settings

**Comment by Jmots2** [comment]
Bash on Windows 10 when running echo %path% reports that idris.exe IS in the path; no joy

**Comment by archaeron** [comment]
Bash on Windows and the official windows path are two different things at
the moment :( it's not yet really possible to use things from bash outside
if it. It should come with the next version of Bash for Windows.

**Comment by Jmots2** [comment]
My bad; windows %path% should include directory path, but apparently NOT the executable itself

**Comment by archaeron** [comment]
glad it's resolved
is it okay if I close the issue? :)
