### ISSUE TITLE
Cannot get documentation or types for operators

### ISSUE THREAD

**Issue by archaeron** [idris-hackers/atom-language-idris#66]
The operators are being sent as they appear in the code, but they need parenthesis around them.

`::` -> `(::)`

**Comment by archaeron** [comment]
correction:
I'ts not the fault of the idris compiler, but of this function:
https://github.com/idris-hackers/atom-language-idris/blob/2beedd92f1a834cce10d060a93a3e3553ce34a2b/lib/idris-controller.coffee#L35-L40

**Comment by david-christiansen** [comment]
Well, we could also make the compiler a bit more permissive on its syntax here :)

**Comment by archaeron** [comment]
What I found out is that operators work sometimes without. I think `<!>` worked, but `::` didn't. Is this posdible?

**Comment by archaeron** [comment]
No, it doesn't work anymore. Strange. But it would be nice if I could just use:
`:t ::`
:)

**Comment by david-christiansen** [comment]
I don't think that it ever worked without the parens...

**Comment by archaeron** [comment]
it did for me. but that could have been anything on my end :D But the issue is resolved now. I check if it's an operator and add two parenthesis :)

**Comment by archaeron** [comment]
I could probably just always add parens

**Comment by david-christiansen** [comment]
Or we can slightly special-case the command parser in the compiler :-) This will make it easier for command-line users as well, so I think that's the better way.

**Comment by archaeron** [comment]
:+1: even better. thanks!
