### ISSUE TITLE
Pass options to idris executable

### ISSUE THREAD

**Issue by edwinb** [idris-hackers/atom-language-idris#74]
Occasionally, I would find it useful to be able to pass arbitrary flags to Idris from Atom, e.g. to turn off the coverage checker or to set language options like --typeintype. Occasionally it would even be nice to add packages with -p, for small demonstration examples where making an ipkg would be overkill.

Is it possible to do this, perhaps just via the settings?

**Comment by archaeron** [comment]
The settings are global, so you'd have to change them for every project.
Or do you mean default settings that you always want?

The package will pick up an ipkg file in a folder. It won't check anything but the `opts`, `sourcedir` and `pkgs` options. So you should even be able to just put a file in your folder with the small demonstration that has `ipkg` as an ending and one or more of the options above, without defining `package`, or `modules` or anything else.

It would be possible to add options that are only considered when the package can't find an `ipkg` file.

**Comment by david-christiansen** [comment]
Just for comparison, the way it works in Emacs is that there's a global setting to which the `ipkg` options are appended for interactive Idris invocations. Also, the global setting can be overridden using Emacs's file or directory variables feature.

**Comment by edwinb** [comment]
Hmm, I wonder if it might be better to be able to set options per file, which would be an Idris feature rather than an editor mode feature.

Even though the setting is global, I think it would occasionally be useful, but maybe I should start by adding language features (like --noprelude) as directives in Idris source files.

**Comment by archaeron** [comment]
It feels a bit dangerous to have settings that are more or less hidden from normal use that are appended automatically. I have the feeling I could get quite some issues reportet with that enabled.

@edwinb having directives like `noprelude` sounds nice to have :)

**Comment by justjoheinz** [comment]
I'll close this issue since we already support for a very long time a subset of ipkg files, namely
 `sourcedir`, `opts` and `pkgs`.
