### ISSUE TITLE
Support Imports

### ISSUE THREAD

**Issue by justjoheinz** [idris-hackers/atom-language-idris#79]
I am not sure, whether this is due to a usage error by myself, or indeed an Atom Idris bug.

When I work on an Idris project and need to import modules from my own code, typechecking (Alt-Ctrl-R) within Atom fails with "can't find import X.Y.Z"

however compiling the code with e.g. idris --build mypackage.ipkg will work and execute the code.

**Comment by archaeron** [comment]
Imports work for me. But it could be a bug nonetheless :)

could you paste your `mypackage.ipkg` here?
in what folder are the source files?

**Comment by justjoheinz** [comment]
```
package optics

modules = Data.Optics.Lens ,
          Data.Optics.Iso ,
          Data.Optics.Prism ,

          Data.Optics.Test

tests = Data.Optics.Test.runall
```
The problem is that I cannot import e.g. Data.Optics.Lens from Data.Optics.Test. I have not specified a dedicated src directory and operate from the root of the project. Here is a list of the file structure:

```
.
├── Data
│   └── Optics
│       ├── Iso.idr
│       ├── Lens.idr
│       ├── Prism.idr
│       └── Test.idr
├── LICENSE
└── optics.ipkg
```

**Comment by justjoheinz** [comment]
Hmm, I removed the project from Atom, quit Atom and restarted and now it works. That was just a hiccup then, I suppose.

**Comment by archaeron** [comment]
Hello

I'm glad it's working now.

Everything looks as it should as far as I can see.
I'm sorry, I can't tell you what went wrong :(

**Comment by archaeron** [comment]
Can I close the issue? :)

**Comment by justjoheinz** [comment]
Of course. Thanks!

2015-10-22 18:03 GMT+02:00 archaeron <notifications@github.com>:

**Comment by archaeron** [comment]
:+1: thank you
