### ISSUE TITLE
Release v.0.1.0

### ISSUE THREAD

**Issue by archaeron** [idris-hackers/atom-language-idris#8]
I'd like to realease the next version.

- @Heather do you know of any bugs?
- @morten do you want to remain official author of this package?
                https://github.com/idris-hackers/atom-language-idris/blob/master/package.json#L13

**Comment by Heather** [comment]
@archaeron I think we should bump it now, no serious bugs I can think about for now.

**Comment by archaeron** [comment]
@Heather pushed the new version https://atom.io/packages/language-idris

**Comment by Heather** [comment]
@archaeron great but version is `0.1.0` there

**Comment by archaeron** [comment]
yes, I made a mistake and instead of releasing a patch version I released a minor version.
Since this is a bit of a new beginning I just left it at that.

**Comment by fangel** [comment]
Sorry, I never got around to answering if I wanted to stay on the author-credits. I would like to remain in some function or another. So maybe change from a single author-entry to multiple contributors, where I can then be one of the contributors and you guys/girls can be the other...

(Also, if anyone updates package.json, it neeeds the updated repository url)

**Comment by archaeron** [comment]
sorry, I never meant to just take over the project.
The idea was always to credit you.
I'll just do something like this:
```json
"author": {
  "name": "Morten Fangel",
  "url": "http://sevengoslings.net"
},
"contributors": [
    { "name": "Nicolas Gagliani", "url": "http://twitter.com/archaeron" },
    { "name": "Heather", "url": "https://github.com/Heather" }
]
```

**Comment by fangel** [comment]
I'm fine with all three of us being contributors - I don't need any special mentions, especially now when you're doing all the maintenance and further development...

**Comment by archaeron** [comment]
updated here:
https://github.com/idris-hackers/atom-language-idris/commit/6d32fe371f41aa9d13c219a995abe89a2d58843b

@fangel @Heather are you okay with it?

**Comment by fangel** [comment]
:+1:

**Comment by Heather** [comment]
:+1:
