### ISSUE TITLE
Inline comment syntax not highlighted correctly

### ISSUE THREAD

**Issue by rpglover64** [idris-hackers/atom-language-idris#85]
```idris
-- foo is a function that = ()
{- foo is a function that = () -}
foo : ()
foo = ()
```

As far as I can tell, the first line of this is highlighted incorrectly (i.e. as a declaration, not as a comment) in the package.

**Comment by archaeron** [comment]
hm, this is strange. I thought I had fixed it here:

https://github.com/idris-hackers/atom-language-idris/commit/1637230613356d30c24d2cac1160457930794b2a

this is how it looks for me:

![idris_comment_highlighting](https://cloud.githubusercontent.com/assets/471043/10984327/e6a7f7a0-8418-11e5-82ef-f8758a028e1f.PNG)


what version of the package are you using?

could you take a screenshot of the issue for me?

**Comment by rpglover64** [comment]
Hmm. I thought I'd updated, but I guess I didn't reload or something.

**Comment by archaeron** [comment]
:+1: my favourite kind of bugfixing :smile:
