### ISSUE TITLE
How to Edit Binary Location in Config?

### ISSUE THREAD

**Issue by kevinmeredith** [idris-hackers/atom-language-idris#89]
The docs say:

>The only thing you might need to set is the path to the idris executable in the config of this package.

When I click `Packages | Idris | Typecheck`, I get the following error:

<img width="458" alt="screen shot 2015-11-20 at 10 31 51 pm" src="https://cloud.githubusercontent.com/assets/1967302/11316470/98c935ca-8fd6-11e5-8f85-a930621c4f13.png">

Could you please tell me which file I should modify to point to the `idris` binary?

Here's what I tried without success:

```
$pwd
/Users/kevin/.atom/packages/language-idris
$find . | grep -i config
./.editorconfig
./node_modules/@cycle/core/.editorconfig
./node_modules/@cycle/core/node_modules/rx/src/core/expressions/web.config
./node_modules/@cycle/core/node_modules/rx/src/core/expressions/web.Debug.config
./node_modules/@cycle/core/node_modules/rx/src/core/expressions/web.Release.config
./node_modules/@cycle/core/node_modules/rx/ts/tsconfig.json
./node_modules/@cycle/dom/.editorconfig
./node_modules/@cycle/dom/node_modules/vdom-to-html/property-config.js
./node_modules/@cycle/dom/node_modules/virtual-dom/.editorconfig
./node_modules/atom-message-panel/.editorconfig
$cat .editorconfig 
# http://editorconfig.org
root = true

[*]
indent_style = space
indent_size = 2
```

Thanks!

**Comment by archaeron** [comment]
Hello
if you go to the settings in atom (Windows: File->Settings) there is left a tab Packages.
If you click there and then search for `language-idris` in the search that appears you should see something like this:
![idris-settings](https://cloud.githubusercontent.com/assets/471043/11317978/ef4f086a-9040-11e5-94c1-62277c6dec60.PNG)

There you can click on `settings` and you're there :)

**Comment by kevinmeredith** [comment]
Thanks!
